### ISSUE TITLE
[REFACTOR] java.time-> kotlinx.datetime

### ISSUE THREAD

**Issue by l2hyunwoo** [sopt-makers/sopt-android#204]
## Level 1 (필수)

- [해당 파일](https://github.com/sopt-makers/sopt-android/blob/develop/app/src/main/java/org/sopt/official/util/GenerationExt.kt)에서 java.time.LocalDateTime을 사용하고 있습니다. kotlinx-serialization에서는 이를 (역)직렬화하지 못하는 문제가 있고, 프로젝트 내 java 의존성을 떨어뜨리고자 하는 목적으로 [kotlinx-datetime](https://github.com/Kotlin/kotlinx-datetime) 패키지로 변환을 하고자 합니다.
- Date를 Parse하는 로직(getGeneration)과 시간 차이를 구하는 로직(computeMothUntilNow)을 kotlinx-datetime을 활용하여 구현해주세요. 
  - 다만 time-formatting은 아직 kotlinx-datetime 내에 구현이 되어있지 않아 toJavaLocalDateTime() + DateTimeFormatter를 활용해주세요.

## Level 2 (심화, 이 레벨부터는 시간이 나실 때 구현하시면 됩니다.)
- getGeneration 함수를 기능확장이 더 편할 수 있게 리팩토링 해주시면 더욱 좋을 것 같습니다

## Level 3 (도전)
- Level 2를 수행하고 도출된 기능에 대한 Unit Test를 작성하여 주세요. 현재 안드로이드 프로젝트의 Test Framework/Library는 아래와 같습니다.
  - JUnit5
  - [Truth](https://github.com/google/truth)

## Reference

- [kotlinx-datetime](https://github.com/Kotlin/kotlinx-datetime)

## Due Date

- 2023.05.15(월) ~ 2023.05.19(금)

**Comment by KwakEuiJin** [comment]
해당 이슈에 관심있습니다. 해결해봐도 괜찮을까요??
