### ISSUE TITLE
[FEAT: SOPTAMP] 스탬프 제출 버튼에 Throttle Click 기능 추가하기

### ISSUE THREAD

**Issue by l2hyunwoo** [sopt-makers/sopt-android#239]
## Problem

현재 SOPTAMP 내 미션 등록 페이지에서 제출 버튼을 동시에 N번 누를 경우 N번 서버통신을 하는 현상이 발생합니다. Modifier에 throttle click 기능을 추가해주세요.

- 해당 페이지는 Compose로 제작되었습니다.

### Due Date

- Task Assigned 된 날 이후로 3일 이내로 PR 제출, 5일 이내로 머지 완료
- 만일 PR 제출 안될 시 assignee가 변경될 수 있습니다.

**Comment by taeheeL** [comment]
제가 도전해봐도 괜찮을까요?

**Comment by l2hyunwoo** [comment]
@taeheeL 이슈 어사인 하겠습니다.
