### ISSUE TITLE
[Feat] Add Baseline Profile in SOPT APP

### ISSUE THREAD

**Issue by l2hyunwoo** [sopt-makers/sopt-android#449]
### Issue

- Baseline Profile을 적용해서 평균시작(Cold Start) 시간을 개선시켜주세요!
- Macrobenchmark를 활용하여 앱 시작시간이 얼마나 개선이 되었는지 측정해주세요.

### Reference

- [Baseline Profiles Overview](https://developer.android.com/topic/performance/baselineprofiles/overview)
- [Measure Baseline Profile](https://developer.android.com/topic/performance/baselineprofiles/measure-baselineprofile)

**Comment by KwakEuiJin** [comment]
🙋‍♂️

**Comment by l2hyunwoo** [comment]
@KwakEuiJin let’s go
