### ISSUE TITLE
[Feat] 로컬 저장소 암호화를 위한 암호화 모듈 만들기

### ISSUE THREAD

**Issue by l2hyunwoo** [sopt-makers/sopt-android#845]
- androidx.security의 이슈로 EncryptedSharedPreferences를 떼어냈으나 로컬 데이터를 평문으로 저장하여 보안상 위험한 상황입니다.
- 데이터를 암호화하여 저장할 수 있는 암호화 저장소 모듈을 제작하여 주세요.

**Comment by jihyunniiii** [comment]
제가 하겠습니닷!!

**Comment by l2hyunwoo** [comment]
감사합니다 @jihyunniiii
